pModel:
  RawData:
    modelName: StratifiedHeatFlowModel
    fmuPath: ..\modelica\ThermalTesters\ThermalTesters_StratifiedHeatFlowModel.fmu
    versionName: v1
    states_default_lower_value: 273.15
    states_default_upper_value: 473.15
    states:
      stratifiedHeatFlow.partition[1].heatCapacitor.T: null
      stratifiedHeatFlow.partition[2].heatCapacitor.T: null
      stratifiedHeatFlow.partition[3].heatCapacitor.T: null
      stratifiedHeatFlow.partition[4].heatCapacitor.T: null
      stratifiedHeatFlow.partition[5].heatCapacitor.T: null
      stratifiedHeatFlow.partition[6].heatCapacitor.T: null
      stratifiedHeatFlow.partition[7].heatCapacitor.T: null
      stratifiedHeatFlow.partition[8].heatCapacitor.T: null
      stratifiedHeatFlow.partition[9].heatCapacitor.T: null
      stratifiedHeatFlow.partition[10].heatCapacitor.T: null
      stratifiedHeatFlow.partition[11].heatCapacitor.T: null
      stratifiedHeatFlow.partition[12].heatCapacitor.T: null
      stratifiedHeatFlow.partition[13].heatCapacitor.T: null
      stratifiedHeatFlow.partition[14].heatCapacitor.T: null
      stratifiedHeatFlow.partition[15].heatCapacitor.T: null
      stratifiedHeatFlow.partition[16].heatCapacitor.T: null
    initial_states_include: true
    initial_states_sampling_strategy: R
    parameters_default_lower_factor: 0.2
    parameters_default_upper_factor: 5.0
    parameters:
      C:
      - 1.8
      R:
      - 1.0
    parameters_include: true
    parameters_sampling_strategy: R
    controls_default_lower_value: 0.2
    controls_default_upper_value: 5.0
    controls:
      temperature_K_a:
      - 273.15
      - 473.15
      temperature_K_b:
      - 273.15
      - 473.15
    controls_include: true
    controls_sampling_strategy: RROCS
    controls_frequency_min_in_timesteps: 6
    controls_frequency_max_in_timesteps: 30
    outputs:
    - stratifiedHeatFlow.partition[1].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[1].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[1].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[2].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[2].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[2].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[3].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[3].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[3].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[4].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[4].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[4].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[5].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[5].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[5].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[6].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[6].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[6].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[7].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[7].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[7].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[8].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[8].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[8].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[9].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[9].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[9].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[10].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[10].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[10].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[11].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[11].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[11].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[12].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[12].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[12].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[13].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[13].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[13].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[14].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[14].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[14].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[15].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[15].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[15].thermalResistor.port_b.Q_flow
    - stratifiedHeatFlow.partition[16].heatCapacitor.port.Q_flow
    - stratifiedHeatFlow.partition[16].thermalResistor.port_a.Q_flow
    - stratifiedHeatFlow.partition[16].thermalResistor.port_b.Q_flow
    Solver:
      simulationStartTime: 0.0
      simulationEndTime: 1.0
      timestep: 0.002
      tolerance: 1.0e-06
      sequence_length: 501
    n_samples: 4096
    creation_date: null
  dataset_prep:
    n_samples:
    - 128
    - 256
    - 512
    - 1024
    - 2048
    - 4096
    transforms: {}
    states:
    - all
    parameters:
    - all
    controls:
    - all
    outputs:
    - all
    start_time: 0.0
    end_time: .inf
    sequence_length: null
    validation_fraction: 0.12
    test_fraction: 0.12
    validation_idx_start: null
    test_idx_start: null
  test_nn_model:
    plot_variables: []
