defaults:
  - base_train_test
  - nn_model: bnode_shf #latent_ode_heatpump
  - _self_

dataset_name: StratifiedHeatFlowModel_v3_c-RROCS__n-1024 #HeatPump_v1_c-RS__n-254 #HeatPump_v1_c-RROCS__n-1023 #StratifiedHeatFlowModel_v3_c-RROCS__n-1024

mlflow_experiment_name: test_variance # heatpump
use_amp: false 
use_cuda: true
raise_exception: true

verbose: true
batch_print_interval: 1
n_workers_train_loader: 2 #8
prefetch_factor: 2
n_workers_other_loaders: 1